---
title: "Parameter Manipulation"
output: ioslides_presentation
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
library(flextable)
library(kableExtra)
```

## Purpose

This presentation is meant to document single parameter manipulations. The main comparison responses are the number of seals at the Gauntlet and the number of salmon escaped total of each species.

## The Base Realm

```{r, message = FALSE, echo = FALSE, warning = FALSE, fig.height = 4, fig.width = 8}
source("Models/Run_The_Model.R", local = knitr::knit_global())
assembleTheLegos(path_to_pars = "Functions/BaseRun_set_pars.R", 
                 path_to_vars = "Functions/BaseRun_initialize_variables.R")
(plot_seals+ theme_classic()) / (eaten_sp_plot+ theme_classic())
salmon_escapement <- data.frame(Sockeye = escape_sockeye[days], Chinook = escape_chinook[days],
                                Coho = escape_coho[days])
kable(salmon_escapement, caption = "Escaped Salmon") %>% kable_styling(full_width = F)
```


## num_seals

```{r, message = FALSE, echo = FALSE, warning = FALSE, fig.height=4, fig.width = 4}
source("Models/Run_The_Model.R", local = knitr::knit_global())

assembleFirstHalf(path_to_pars = "Functions/BaseRun_set_pars.R")

num_seals_list <- seq(from = 1, to = 75, by = 5)

Escape <- data_frame(Seals = 0, Sockeye = 0, Chinook = 0, Coho = 0)
for(i in 1:length(num_seals_list)){
  num_seals <- num_seals_list[i]
  assembleSecondHalf(path_to_vars = "Functions/BaseRun_initialize_variables.R")
  Escape[i,] <- data_frame(Seals = num_seals, salmon_escapement)
}

Escape <- data_frame(Escape)

plot_escape_manipulations <- ggplot(data = Escape, aes(x = Seals)) +
  geom_line(aes(y = Chinook), color = "seagreen") + 
  geom_line(aes(y = Coho), color = "goldenrod") + 
  geom_line(aes(y = Sockeye), color = "salmon") +
  labs(y = "Salmon Escaped", x = "Number of Seals in Source Pool")
plot_escape_manipulations

```

Declines to a minimum value, likely governed by the predator dependence/competition level.


## Slide with R Output

```{r cars, echo = TRUE}
summary(cars)
```

## Slide with Plot

```{r pressure}
plot(pressure)
```

